# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blender.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'blender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rblender.proto\x12\x07\x62lender\"=\n\x08Viewport\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\" \n\rImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0cImageService\x12\x39\n\x0cReceiveImage\x12\x11.blender.Viewport\x1a\x16.blender.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIEWPORT']._serialized_start=26
  _globals['_VIEWPORT']._serialized_end=87
  _globals['_IMAGERESPONSE']._serialized_start=89
  _globals['_IMAGERESPONSE']._serialized_end=121
  _globals['_IMAGESERVICE']._serialized_start=123
  _globals['_IMAGESERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
