######################################################################
# Automatically generated by qmake (3.1) Tue Nov 19 10:56:03 2024
######################################################################

TEMPLATE = app
TARGET = qt5libvnc
QT += widgets
INCLUDEPATH += .
INCLUDEPATH += ./../../include/
LIBS += -L./../../libs -lvncclient

#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
# Input
SOURCES += qt5client.cpp
