######################################################################
# Automatically generated by qmake (3.1) Tue Nov 19 14:12:55 2024
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .
QT += widgets
INCLUDEPATH += ./../include/
LIBS += -L./../libs -lvncclient

# Input
SOURCES += main.cpp
